# Redis 服务器地址
spring.data.redis.host:localhost
  # Redis 端口 (默认 6379)
spring.data.redis.port:6379
  # 密码 (如果设置了)
  # spring.data.redis.password=yourpassword
  # 数据库索引 (默认 0)
  # spring.data.redis.database=0
  # 连接超时时间 (毫秒)
spring.data.redis.timeout:5000